# Generated by Django 4.2.7 on 2025-08-27 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Категория прайс-лист',
                'verbose_name_plural': '1.1) Категории прайс-лист',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Certificates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='photos/certificates', verbose_name='Сертификаты')),
            ],
            options={
                'verbose_name': 'Сертификаты',
                'verbose_name_plural': '3) Сертификаты',
            },
        ),
        migrations.CreateModel(
            name='ImageCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Категории фото',
                'verbose_name_plural': '2.1) Категория фото',
            },
        ),
        migrations.CreateModel(
            name='Immutable_content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('content', models.TextField(blank=True, verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'Не изменяемый контент',
                'verbose_name_plural': '5) Не изменяемый контент',
            },
        ),
        migrations.CreateModel(
            name='PrivacyPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='название политики конфиденциальности')),
                ('description', models.TextField(verbose_name='описание политики конфиденциальности')),
            ],
            options={
                'verbose_name': 'Политика конфиденциальности',
                'verbose_name_plural': 'Политика конфиденциальности',
            },
        ),
        migrations.CreateModel(
            name='SiteContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_name', models.CharField(help_text='О чем текст', max_length=80, unique=True, verbose_name='Название')),
                ('description', models.TextField(help_text='Содержимое для мета-тега description', verbose_name='Контент')),
            ],
            options={
                'verbose_name': 'Текст мета-тега',
                'verbose_name_plural': '6) Для мета-тега',
            },
        ),
        migrations.CreateModel(
            name='ThirdPartyDataTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(verbose_name='причина передачи данных третьим лицам')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saloon.privacypolicy', verbose_name='ссылка на политику конфиденциальности, к которой относится передача данных')),
            ],
            options={
                'verbose_name': 'Политика конфиденциальности, причины передачи данных третьим лицам',
                'verbose_name_plural': '4) Политика конфиденциальности, причина передачи данных третьим лицам',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название подкатегории')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='saloon.category', verbose_name='Категории')),
            ],
            options={
                'verbose_name': 'Подкатегория прайс-лист',
                'verbose_name_plural': '1.2) Подкатегории прайс-лист',
            },
        ),
        migrations.CreateModel(
            name='PriceList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_title', models.CharField(max_length=255, verbose_name='Название процедуры')),
                ('min_price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Минимальная цена')),
                ('max_price', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='Максимальная цена')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='saloon.subcategory', verbose_name='Подкатегории')),
            ],
            options={
                'verbose_name': 'Прайс-лист',
                'verbose_name_plural': '1) Прайс-лист',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='photos/%Y/%m/%d', verbose_name='Фото работ')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saloon.imagecategory', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Фото работ',
                'verbose_name_plural': '2) Фото работ',
            },
        ),
        migrations.CreateModel(
            name='DataCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField(max_length=200, verbose_name='Данные, подлежащие сбору')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saloon.privacypolicy', verbose_name='ссылка на политику конфиденциальности, к которой относится сбор данных')),
            ],
            options={
                'verbose_name': 'Политика конфиденциальности, данные подлежащие сбору',
                'verbose_name_plural': '4) Политика конфиденциальности, данные подлежащие сбору',
            },
        ),
    ]
